# Generated by Django 6.0.2 on 2026-03-01 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(help_text='e.g. Entomology, Plant Pathology', max_length=255)),
                ('qualification', models.TextField()),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('organization_association', models.CharField(blank=True, help_text='Current workplace or association', max_length=255, null=True)),
                ('is_verified_by_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'expert'}, on_delete=django.db.models.deletion.CASCADE, related_name='expert_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpertAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice_en', models.TextField(verbose_name='Professional Advice (English)')),
                ('advice_bn', models.TextField(verbose_name='Professional Advice (Bangla)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagnostic_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_advices', to='core.diagnostichistory')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advices', to='experts.expertprofile')),
            ],
        ),
    ]
