# Generated by Django 6.0.2 on 2026-03-28 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0002_alter_expertadvice_id_alter_expertprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertadvice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
