# Generated by Django 6.0.2 on 2026-03-12 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_diagnostichistory_crop_diagnostichistory_disease_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostichistory',
            name='disease',
        ),
    ]
