# Generated by Django 6.0.2 on 2026-03-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_diagnostichistory_disease'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnostichistory',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'DiagnosticHistories'},
        ),
        migrations.AlterField(
            model_name='diagnostichistory',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
