# Generated by Django 6.0.2 on 2026-03-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_diagnostichistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostichistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
