# Generated by Django 5.1.7 on 2026-03-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_communitypost_related_diagnosis_alter_comment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostichistory',
            name='ai_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
