# Generated by Django 5.1.7 on 2026-03-13 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_diagnostichistory_ai_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('badge_type', models.CharField(choices=[('post', 'পোস্ট'), ('scan', 'স্ক্যান'), ('comment', 'মন্তব্য')], max_length=10)),
                ('required_count', models.IntegerField()),
                ('icon', models.CharField(default='🏅', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='related_diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_posts', to='core.diagnostichistory'),
        ),
    ]
